# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdappp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmodel',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
