# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-23 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdappp', '0002_auto_20190321_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createmodel',
            name='image',
        ),
    ]
